project:
  awsSetup:
    bucket: projects.irll
    containerName: test-option-metrics-complexity
    cpu: 2
    memory: 8
    region: ca-central-1
    repository: test-option-metrics-complexity
    repositoryUri: 237796709103.dkr.ecr.ca-central-1.amazonaws.com/test-option-metrics-complexity
    rootDomain: irll.net
  bucket: projects.irll
  ecsTask: test-option-metrics-complexity
  events:
    startServerStep: 1
    stopServerStep: 4
  id: test-option-metrics-complexity
  live: true
  maxRuntime: 90
  name: option-metrics-complexity
  researcher: Federico Mathis
  ssl:
    fullchain: SSL/fullchain.pem
    privkey: SSL/privkey.pem
    sslBucket: projects.irll
  steps:
    1: Consent.html
    2: PreSurvey.html
    3: game
    4: PostSurvey.html
    5: Thank.html
    finalStep: Thank.html
  teamMembers: Federico Mathis, Petrich Laura
  useAWS: true
trial:
  actionBufferLifespan: 1
  actionSpace: []
  allowFrameRateChange: false
  bucket: projects.irll
  dataFile: episode
  defaultAction: null
  defaultStart: true
  frameRateStepSize: 5
  game: MineCrafting
  maxEpisodes: 2
  maxFrameRate: 60
  minFrameRate: 1
  projectId: test-option-metrics-complexity
  s3upload: true
  startingFrameRate: 15
  ui:
  - reset
  variables:
    gameWindowHeight: 719
    gameWindowSize: responsive
    gameWindowWidth: 1056
