project:
  awsSetup:
    bucket: projects.irll
    containerName: fingerprint-demo
    cpu: 2
    memory: 10
    region: ca-central-1
    repository: fingerprint-demo
    repositoryUri: 237796709103.dkr.ecr.ca-central-1.amazonaws.com/fingerprint-demo
    rootDomain: irll.net
  bucket: projects.irll
  ecsTask: fingerprint-demo
  events:
    startServerStep: 1
    stopServerStep: 3
  id: fingerprint-demo
  live: true
  maxRuntime: 30
  name: fingerprint-demo
  researcher: Nadeen
  ssl:
    fullchain: SSL/fullchain.pem
    privkey: SSL/privkey.pem
    sslBucket: projects.irll
  steps:
    1: exampleConsent.html
    2: game
    3: exampleThank.html
    finalStep: exampleThank.html
  teamMembers: null
  useAWS: true
trial:
  actionBufferLifespan: 1
  actionSpace: null
  allowFrameRateChange: false
  bucket: projects.irll
  dataFile: episode
  fingerprint: true
  frameRateStepSize: 5
  game: fingerprint
  instructions:
  - Click on "Add Marker" and select target location on image to add a marker
  - Scroll (mouse), pinch (touchpad/mousepad), double-click or use control keys to
    zoom
  - Click and drag to move
  - Use sliders to adjust image appearance
  maxEpisodes: 20
  maxFrameRate: 60
  maxScore: 2242
  minFrameRate: 1
  minMinutiae: 1
  projectId: fingerprint-demo
  s3upload: false
  startingFrameRate: 30
  ui:
  - stop
  - brightness
  - contrast
  - saturation
  - hue
  - undo
  - redo
  - addMinutia
  - resetImage
  - submitImage
