project:
  awsSetup:
    bucket: null
    cpu: 2
    memory: 10
    region: null
    rootDomain: null
  events:
    startServerStep: null
    stopServerStep: null
  id: null
  live: true
  maxRuntime: 60
  name: null
  researcher: null
  ssl:
    fullchain: SSL/fullchain.pem
    privkey: SSL/privkey.pem
    sslBucket: null
  steps:
    1: null
    2: null
    3: null
    4: null
    5: null
    finalStep: null
  teamMembers: null
  useAWS: false
trial:
  actionBufferLifespan: 1
  actionSpace:
  - noop
  - up
  - right
  - left
  - down
  - upright
  - upleft
  - downright
  - downleft
  allowFrameRateChange: true
  bucket: null
  dataFile: episode
  frameRateStepSize: 5
  game: MineCrafting
  maxEpisodes: 20
  maxFrameRate: 60
  minFrameRate: 1
  projectId: null
  s3upload: false
  startingFrameRate: 30
  ui:
  - start
  - stop
  - reset
  - fpsSet
  - fpsUp
  - fpsDown
  variables:
    gameWindowHeight: 719
    gameWindowSize: responsive
    gameWindowWidth: 1056
