project:
  awsSetup:
    bucket: null
    cpu: 2
    memory: 10
    region: null
    rootDomain: null
  events:
    startServerStep: null
    stopServerStep: null
  id: null
  live: true
  maxRuntime: 60
  name: null
  researcher: null
  ssl:
    fullchain: SSL/fullchain.pem
    privkey: SSL/privkey.pem
    sslBucket: null
  steps:
    1: StepFiles/exampleConsent.html
    2: null
    3: StepFiles/exampleQuiz.html
    4: StepFiles/exampleSurvey.html
    finalStep: StepFiles/exampleThank.html
  teamMembers: null
  useAWS: false
trial:
  actionBufferLifespan: 1
  actionSpace:
  - noop
  - up
  - right
  - left
  - down
  - upright
  - upleft
  - downright
  - downleft
  allowFrameRateChange: false
  bucket: null
  dataFile: episode
  defaultAction: null
  defaultStart: true
  frameRateStepSize: 5
  game: MineCrafting
  maxEpisodes: 20
  maxFrameRate: 60
  minFrameRate: 1
  projectId: null
  s3upload: false
  startingFrameRate: 30
  ui: []
  variables:
    gameWindowHeight: 719
    gameWindowSize: responsive
    gameWindowWidth: 1056
