project:
  id: test-option-metrics-complexity # Letters, Numbers and '-' only!
  useAWS: True # bool, set to true if using AWS, set false and ignore all AWS entries
  awsSetup:
    bucket: projects.irll
    region: ca-central-1
    rootDomain: irll.net
    cpu: 2 # int 1,2, or 4
    memory: 8 # int 1-30
  events:
    startServerStep: 1 # int
    stopServerStep: 4 # int
  live: True # bool
  maxRuntime: 90 # int in minutes.
  name: option-metrics-complexity # str
  researcher: Federico Mathis # str
  ssl:
    sslBucket: projects.irll
    fullchain: SSL/fullchain.pem
    privkey: SSL/privkey.pem
  steps: # any number of steps needed with corresponding filenames
    1: StepFiles/Consent.html
    2: StepFiles/PreSurvey.html
    3: game
    4: StepFiles/PostSurvey.html
    5: StepFiles/Thank.html
    finalStep: StepFiles/Thank.html # required, filename can be same as last numbered step
  teamMembers: Federico Mathis, Petrich Laura # str
trial:
  actionBufferLifespan: 1 # int
  maxEpisodes: 2 # int
  game: MineCrafting # full environment name
  dataFile: episode # episode or trial
  s3upload: True
  actionSpace: []
  frameRateStepSize: 5 # int Optional if allowFrameRateChange = False
  minFrameRate: 1 # int Optional if allowFrameRateChange = False
  maxFrameRate: 60 # int Optional if allowFrameRateChange = False
  allowFrameRateChange: False # bool
  startingFrameRate: 15 # int Required
  defaultStart: True
  defaultAction:
  ui: # to include ui button set to True, False buttons will not be shown
    left: False
    right: False
    up: False
    down: False
    start: False
    stop: False
    pause: False
    reset: True
    trainOffline: False
    trainOnline: False
    good: False
    bad: False
    fpsSet: False
    fpsUp: False
    fpsDown: False
  variables:
    gameWindowWidth: 1056 # int in pixels
    gameWindowHeight: 719 # int in pixels
    gameWindowSize: responsive # str options are 'strict' or 'responsive'

