trial:
  actionBufferLifespan: 1
  actionSpace: null
  allowFrameRateChange: false
  bucket: null
  dataFile: episode
  frameRateStepSize: 5
  game: fingerprint
  instructions:
  - Select a marker to edit it
  - Scroll (mouse), pinch (touchpad/mousepad), or use arrow keys to zoom
  - Drag or use space + arrow keys to move
  maxEpisodes: 20
  maxFrameRate: 60
  minFrameRate: 1
  projectId: null
  s3upload: false
  startingFrameRate: 30
  ui:
  - brightness
  - contrast
  - saturation
  - hue
  - undo
  - redo
  - addMarker
  - resetImage
  - submitImage
