trial:
  actionBufferLifespan: 1
  actionSpace: []
  allowFrameRateChange: false
  bucket: null
  dataFile: episode
  defaultAction: null
  defaultStart: true
  frameRateStepSize: 5
  game: MineCrafting
  maxEpisodes: 2
  maxFrameRate: 60
  minFrameRate: 1
  projectId: null
  s3upload: false
  startingFrameRate: 15
  ui: []
  variables:
    gameWindowHeight: 719
    gameWindowSize: responsive
    gameWindowWidth: 1056
