trial:
  actionBufferLifespan: 1
  actionSpace: []
  allowFrameRateChange: false
  bucket: projects.irll
  dataFile: episode
  defaultAction: null
  defaultStart: true
  frameRateStepSize: 5
  game: MineCrafting
  maxEpisodes: 2
  maxFrameRate: 60
  minFrameRate: 1
  projectId: test-option-metrics-complexity
  s3upload: true
  startingFrameRate: 15
  ui:
  - reset
  variables:
    gameWindowHeight: 719
    gameWindowSize: responsive
    gameWindowWidth: 1056
