trial:
  actionBufferLifespan: 1
  actionSpace:
  - noop
  - up
  - right
  - left
  - down
  - upright
  - upleft
  - downright
  - downleft
  allowFrameRateChange: false
  bucket: null
  dataFile: episode
  defaultAction: null
  defaultStart: true
  frameRateStepSize: 5
  game: MineCrafting
  maxEpisodes: 20
  maxFrameRate: 60
  minFrameRate: 1
  projectId: null
  s3upload: false
  startingFrameRate: 30
  ui:
  - librairy
  variables:
    gameWindowHeight: 719
    gameWindowSize: responsive
    gameWindowWidth: 1056
